/* 
**  mod_mod_rx.c -- Apache sample mod_rx module
**  [Autogenerated via ``apxs -n mod_rx -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_mod_rx.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /mod_rx in as follows:
**
**    #   httpd.conf
**    LoadModule mod_rx_module modules/mod_mod_rx.so
**    <Location /mod_rx>
**    SetHandler mod_rx
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /mod_rx and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/mod_rx 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_mod_rx.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

/* The sample content handler */
static int mod_rx_handler(request_rec *r)
{
    if (strcmp(r->handler, "mod_rx")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_mod_rx.c\n", r);
    return OK;
}

static void mod_rx_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(mod_rx_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA mod_rx_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    mod_rx_register_hooks  /* register hooks                      */
};

uint32_t lruc_hash(lruc *cache, void *key, uint32_t key_length)
{
  uint32_t m = 0x5bd1e995;
  uint32_t r = 24;
  uint32_t h = cache->seed ^ key_length;
  char *data = (char *)key;

  while (key_length >= 4) {
    uint32_t k = *(uint32_t *)data;
    k *= m;
    k ^= k >> r;
    k *= m;
    h *= m;
    h ^= k;
    data += 4;
    key_length -= 4;
  }

  switch (key_length) {
  case 3:
    h ^= data[2] << 16;
  case 2:
    h ^= data[1] << 8;
  case 1:
    h ^= data[0];
    h *= m;
  };

  h ^= h >> 13;
  h *= m;
  h ^= h >> 15;
  return h % cache->hash_table_size;
}

